### ISSUE TITLE
QA Toolkit - Audit Source of Project Deletion

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#420]
#### Original request from stakeholder sent via email on 7/31/2018 indicating two (2) additional projects have had a hard delete from the Toolkit. 

1. Please research / audit the deleted projects to **_identify who/how the project records were deleted_** 

     - Is there a way to confirm for certain that the delete is being initiated by a user and not the system…potentially through restoring a database backup or similar process? 

    - One of the users project appears it may have been previously accessed as recently as 7/6

2. Assess potential development of a solution to record **_who/how has initiated a hard delete_** from the system within in some sort of simple log that could be accessed by Tad or similar user.

**Comment by slmessier** [comment]
@vijme - Tad has provided notice to proceed (via email 8/9/2018) to:

**_Update system role permissions  to restrict the project delete functionality exclusively for ESC Manager and/or admin roles._** 

Please update in DEV, then assign to @HollySchuelerKCI for testing.

**Comment by vijme** [comment]
Project Delete button available exclusively for ESC Manager Role from the project List page. 

(However, please note that admins can go through the admin page -> Data Cleanup -> Project Dups to delete a project. )

**Comment by slmessier** [comment]
@Tad-Daniel please test / confirm using the DEV application instance:
[http://oed.kci.com/SHAPORTAL/](http://oed.kci.com/SHAPORTAL/)

**Comment by Tad-Daniel** [comment]
I just checked all the roles and everything appears correct.

**Comment by slmessier** [comment]
@Tad-Daniel Thank you. Fix is available in STAGING. **Please test / confirm using the STAGING application instance:**
[http://199.107.71.85/shaportal/](http://199.107.71.85/shaportal/)

**Comment by Tad-Daniel** [comment]
I tested in staging and it is still happening.    logged in as "inspector role"   when I reset the search field under the projects tab the delete button appeared

**Comment by vijme** [comment]
This is a latest issue logged as #479 and had been fixed in dev. The fix is not available in staging yet.
